### ISSUE TITLE
support multipoint output

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/stacIndexer#18]
Return an array.
```
"bbox": [-149.2133, 42.5369, -72.1727, 63.8758],
  "geometry": {
    "type": "MultiPoint",
    "coordinates": [
      [-72.1727, 42.5369],
      [-149.2133, 63.8758]
    ]
  },
```

IN the STAC SPEC, geometry is actually a geojson. with a LON LAT. Coordinates need to be flpped (lat lon) [SOS Spec](https://github.com/ESIPFed/science-on-schema.org/blob/main/guides/Dataset.md#use-geoshape-for-all-other-location-types)

https://github.com/ESIPFed/science-on-schema.org/blob/main/guides/Dataset.md#handling-multiple-locations

https://raw.githubusercontent.com/eco4cast/neon4cast-ci/main/catalog/scores/Phenology/Daily_Green_chromatic_coordinate/models/ChlorophyllCrusaders.json

**Comment by valentinedwv** [comment]
Possible, but will not render until added to facetsearch datasetlocation

{
      "@type": "GeoShape",
      "geosparql:asWKT": {
        "@value": "MULTIPOINT ((10 40), (40 30), (20 20), (30 10))",
        "@type": "geosparql:wktLiteral"
      },

**Comment by ylyangtw** [comment]
close as it's done
