### ISSUE TITLE
Schema changes

### ISSUE THREAD

**Issue by ylyangtw** [earthcube/stacIndexer#22]
- [x] Use property title for titles
- [x] Use property start datetime instead of published year - also, the year filter is not working

**Comment by valentinedwv** [comment]
Published Year. All the same. Are they not updating that? Just make them aware for 'future' forecast projects they should update it to the challenge start.

We might add a temporal facet to search for things like starttime. But for modeling, dates a forecast applies, can be different that when published.

**Comment by ylyangtw** [comment]
> Published Year. All the same. Are they not updating that? Just make them aware for 'future' forecast projects they should update it to the challenge start.
> 
> We might add a temporal facet to search for things like starttime. But for modeling, dates a forecast applies, can be different that when published.

In their json, there is no published Year. It was me putting some placeholder there. I am going to use starttime for it.

**Comment by ylyangtw** [comment]
Close as the json files are updated. Created another issue for range bar in the UI https://github.com/earthcube/facetsearch/issues/148
